# Generated by Django 5.2.12 on 2026-03-06 07:05

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：生产环境主账号', max_length=50, verbose_name='账号名称/别名')),
                ('access_key', models.CharField(max_length=100, verbose_name='AccessKey ID')),
                ('secret_key', fernet_fields.fields.EncryptedCharField(max_length=100, verbose_name='AccessKey Secret')),
                ('region', models.CharField(default='cn-hangzhou', max_length=50, verbose_name='默认区域')),
                ('type', models.CharField(choices=[('aliyun', '阿里云 (Aliyun)'), ('tencent', '腾讯云 (Tencent)')], default='aliyun', max_length=20, verbose_name='云厂商')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighRiskAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='高危命令')),
                ('risk_level', models.CharField(default='High', max_length=20, verbose_name='风险等级')),
                ('ai_advice', models.TextField(blank=True, null=True, verbose_name='AI评估建议')),
                ('action', models.CharField(choices=[('blocked', '拦截/取消'), ('executed', '强制执行')], default='blocked', max_length=20, verbose_name='最终动作')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '高危审计',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP地址')),
                ('port', models.IntegerField(default=22, verbose_name='SSH端口')),
                ('username', models.CharField(default='root', max_length=50, verbose_name='SSH用户名')),
                ('password', fernet_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True, verbose_name='SSH密码')),
                ('cpu_cores', models.IntegerField(default=1, verbose_name='CPU核数')),
                ('memory_gb', models.IntegerField(default=1, verbose_name='内存(GB)')),
                ('os_name', models.CharField(default='CentOS 7.9', max_length=100, verbose_name='操作系统')),
                ('provider', models.CharField(choices=[('aliyun', '阿里云'), ('private', '私有/物理机')], default='private', max_length=20, verbose_name='来源')),
                ('instance_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='实例ID')),
                ('status', models.CharField(choices=[('Running', '运行中'), ('Stopped', '已停止')], default='Running', max_length=20, verbose_name='状态')),
                ('use_agent', models.BooleanField(default=False, help_text='开启后将停止SSH采集，等待Agent上报', verbose_name='使用Agent')),
                ('agent_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Agent Token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='组名')),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroupAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ServerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField(default=0.0, verbose_name='CPU使用率')),
                ('mem_usage', models.FloatField(default=0.0, verbose_name='内存使用率')),
                ('disk_usage', models.FloatField(default=0.0, help_text='/ 分区', verbose_name='磁盘使用率')),
                ('load_1min', models.FloatField(default=0.0, verbose_name='1分钟负载')),
                ('net_in', models.FloatField(default=0.0, verbose_name='入站流量')),
                ('net_out', models.FloatField(default=0.0, verbose_name='出站流量')),
                ('disk_read_rate', models.FloatField(default=0.0, verbose_name='磁盘读取速率(KB/s)')),
                ('disk_write_rate', models.FloatField(default=0.0, verbose_name='磁盘写入速率(KB/s)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='SSLCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True, verbose_name='域名')),
                ('port', models.IntegerField(default=443, verbose_name='端口')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='颁发机构')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='签发时间')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('remaining_days', models.IntegerField(default=0, verbose_name='剩余天数')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('auto_alert', models.BooleanField(default=True, verbose_name='自动告警')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后检测时间')),
            ],
            options={
                'verbose_name': 'SSL证书',
                'verbose_name_plural': 'SSL证书',
            },
        ),
        migrations.CreateModel(
            name='TerminalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100, verbose_name='WebSocket频道')),
                ('log_file', models.FileField(blank=True, null=True, upload_to='ssh_logs/%Y/%m/%d/', verbose_name='录像文件')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
