# Generated by Django 5.2.12 on 2026-03-06 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cmdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='highriskaudit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AddField(
            model_name='highriskaudit',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.server', verbose_name='服务器'),
        ),
        migrations.AddField(
            model_name='servergroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cmdb.servergroup', verbose_name='上级分组'),
        ),
        migrations.AddField(
            model_name='server',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.servergroup', verbose_name='所属分组'),
        ),
        migrations.AddField(
            model_name='servergroupauth',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_group_auths', to='auth.group', verbose_name='角色'),
        ),
        migrations.AddField(
            model_name='servergroupauth',
            name='server_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.servergroup', verbose_name='服务器分组'),
        ),
        migrations.AddField(
            model_name='servermetric',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='cmdb.server'),
        ),
        migrations.AddField(
            model_name='terminallog',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.server', verbose_name='服务器'),
        ),
        migrations.AddField(
            model_name='terminallog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作人'),
        ),
        migrations.AlterUniqueTogether(
            name='servergroupauth',
            unique_together={('role', 'server_group')},
        ),
    ]
