# Generated by Django 5.2.12 on 2026-03-06 07:05

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如: DeepSeek-V3, GPT-4', max_length=50, verbose_name='模型别名')),
                ('model_name', models.CharField(help_text='API调用的模型名, 如: deepseek-chat, gpt-3.5-turbo', max_length=50, verbose_name='模型标识')),
                ('api_key', fernet_fields.fields.EncryptedCharField(max_length=200, verbose_name='API Key')),
                ('base_url', models.CharField(default='https://api.openai.com/v1', max_length=200, verbose_name='Base URL')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI')], max_length=10)),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新会话', max_length=100, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_ops.aimodel')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
